sudo: false
language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
